"""Archived example post. Slides are pre-rendered HTML strings; new posts should use the helpers in tools/lib.py."""
import sys, pathlib; sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[2] / "tools"))
from lib import *

ACCOUNT = 'dollartrail'
TRAIL = '001'
FOLLOWING = '1 gal. regular'
SOURCES = ['https://www.eia.gov/energyexplained/gasoline/factors-affecting-gasoline-prices.php']

CAPTION = 'You paid $3.10 for a gallon of regular. ...'

SLIDES = [
    '<div class=tag>Trail No. 001</div>\n<div class=hook>You paid <em>$3.10</em><br>for a gallon<br>of gas.</div>\n<div class=hook2>Here\'s who actually<br>got your money.</div>\n<div class=mini style="margin-top:60px">Source: U.S. Energy Information Administration &middot; 2025 U.S. average, regular grade</div>',
    '<div class=tag>The trail map</div>\n<h2 style="font-size:70px">One gallon.<br>Four stops.</h2>\n<div class=wrap>\n <div class=gallon>\n  <div class=seg style="height:128px;background:#f2b84b">18%</div>\n  <div class=seg style="height:120px;background:#c9c5ba">17%</div>\n  <div class=seg style="height:103px;background:#6aa9ff">14%</div>\n  <div class=seg style="flex:1;background:#ff5a4e;font-size:48px">51%</div>\n </div>\n <div class=legend>\n  <div class=lg><span class=k><i style="background:#ff5a4e"></i>Crude oil</span><span class=v>$1.59</span></div>\n  <div class=lg><span class=k><i style="background:#f2b84b"></i>Distribution &amp; retail</span><span class=v>$0.55</span></div>\n  <div class=lg><span class=k><i style="background:#c9c5ba"></i>Taxes</span><span class=v>$0.51</span></div>\n  <div class=lg><span class=k><i style="background:#6aa9ff"></i>Refining</span><span class=v>$0.44</span></div>\n  <div class=lg><span class=k><i style="background:transparent"></i>Total</span><span class=v>$3.10</span></div>\n  <div class=mini>Dollar figures = EIA\'s 2025 percentage shares applied to the $3.10 average. Rounded.</div>\n </div>\n</div>',
    '<div class="tag ghost" style="color:#ff5a4e;border-color:#ff5a4e">Stop 1 of 4</div>\n<h2>Crude oil</h2><div class=amt style="color:#ff5a4e">$1.59</div><div class=pct>51% OF EVERY GALLON</div><p>More than half your gallon is raw crude, priced on a global market.</p><p>Before anything is refined, trucked or taxed, <b>half the money has already left town.</b></p>\n<div class=finding><div class=lab>Trail note</div><div class=t>Crude is the biggest piece, so it\'s usually the first suspect when prices jump.</div></div>',
    '<div class="tag ghost" style="color:#f2b84b;border-color:#f2b84b">Stop 2 of 4</div>\n<h2>Getting it to you</h2><div class=amt style="color:#f2b84b">$0.55</div><div class=pct>18% OF EVERY GALLON</div><p>Pipeline to a terminal. Blending with ethanol. A tanker truck to the station.</p><p>Then the station itself: <b>rent, wages, insurance, equipment</b>, and whatever profit is left over.</p>\n<div class=finding><div class=lab>Trail note</div><div class=t>This is why two stations on opposite corners can charge different prices.</div></div>',
    '<div class="tag ghost" style="color:#c9c5ba;border-color:#c9c5ba">Stop 3 of 4</div>\n<h2>Taxes</h2><div class=amt style="color:#c9c5ba">$0.51</div><div class=pct>17% OF EVERY GALLON</div>\n<div class=taxrow>\n <div class=tx><div class=l>Federal</div><div class=n>18.4&cent;</div><div class=d>Flat, per gallon. Not raised since 1993.</div></div>\n <div class=tx><div class=l>State (avg.)</div><div class=n>33.6&cent;</div><div class=d>Average across states, Jan. 2026. Some add local and sales tax.</div></div>\n</div>\n<div class=finding><div class=lab>Trail note</div><div class=t>Because it\'s cents per gallon, not a percentage, the federal tax takes the same bite whether gas costs $2 or $5.</div></div>',
    '<div class="tag ghost" style="color:#6aa9ff;border-color:#6aa9ff">Stop 4 of 4</div>\n<h2>Refining</h2><div class=amt style="color:#6aa9ff">$0.44</div><div class=pct>14% OF EVERY GALLON</div><p>Turning crude into gasoline. This slice is refinery <b>costs and profits</b> combined.</p><p>It swings by season and region, partly because different areas require different cleaner-burning blends.</p>\n<div class=finding><div class=lab>Trail note</div><div class=t>Demand rises in summer, and summer blends cost more to make. Expect this slice to grow when it\'s warm.</div></div>',
    '<div class=tag>Detour</div>\n<h2>The upgrade<br>at the pump</h2>\n<div class=cmp>\n <div class=cb><div class=lbl>$3.10</div><div class=col style="height:78%"></div></div>\n <div class=cb><div class=lbl>+57&cent;</div><div class=col style="height:92%"></div></div>\n <div class="cb hot"><div class=lbl>+93&cent;</div><div class=col style="height:100%"></div></div>\n</div>\n<div class=xax><span>Regular</span><span>Midgrade</span><span>Premium</span></div>\n<div class=finding style="margin-top:30px"><div class=lab>Trail note</div><div class=t>Premium averaged about 93&cent; more than regular in 2025, roughly a 30% markup. If your owner\'s manual says premium is <i>recommended</i>, not <i>required</i>, read it before you pay that.</div></div>',
    '<div class=tag>End of the trail</div>\n<div class=hook style="font-size:96px">Half crude.<br>A third taxes<br>and transport.<br><em>A slice of refining.</em></div>\n<div class=cta>Send this to the friend<br>who blames the <em>gas station.</em></div>\n<div class=src>Follow @dollartrail: we follow one price to the end, every day.<br><br>Source: U.S. EIA, &ldquo;Factors affecting gasoline prices&rdquo; (2025 averages; state tax as of Jan. 2026).</div>',
]
