"""Archived example post. Slides are pre-rendered HTML strings; new posts should use the helpers in tools/lib.py."""
import sys, pathlib; sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[2] / "tools"))
from lib import *

ACCOUNT = 'dollartrail'
TRAIL = '002'
FOLLOWING = '$1 of federal spending'
SOURCES = ['https://www.cbo.gov/publication/61307']

CAPTION = '$7 trillion spent in fiscal year 2025. ...'

SLIDES = [
    '<div class=tag>Trail No. 002</div>\n<div class=hook style="font-size:122px">The government spent <em>$7 trillion</em> last year.</div>\n<div class=hook2>Here\'s where each dollar went.</div>\n<div class=mini style="margin-top:40px">Source: Congressional Budget Office, Monthly Budget Review, fiscal year 2025 (Oct. 2024 to Sept. 2025)</div>',
    '<div class=tag>The trail map</div><h2 style="font-size:70px">One dollar.<br>Seven stops.</h2>\n<div class=wrap><div class=gallon style="height:760px"><div class=seg style="height:167px;background:#ff5a4e;font-size:30px">22¢</div><div class=seg style="height:114px;background:#f2b84b;font-size:30px">15¢</div><div class=seg style="height:106px;background:#6aa9ff;font-size:30px">14¢</div><div class=seg style="height:91px;background:#c9c5ba;font-size:30px">12¢</div><div class=seg style="height:76px;background:#b98cff;font-size:30px">10¢</div><div class=seg style="height:38px;background:#4fd1a5;font-size:22px">5¢</div><div class=seg style="height:167px;background:#8c9097;font-size:30px">22¢</div></div><div class=legend><div class=lg><span class=k><i style="background:#ff5a4e"></i>Social Security</span><span class=v>22¢</span></div><div class=lg><span class=k><i style="background:#f2b84b"></i>Interest on the debt</span><span class=v>15¢</span></div><div class=lg><span class=k><i style="background:#6aa9ff"></i>Medicare</span><span class=v>14¢</span></div><div class=lg><span class=k><i style="background:#c9c5ba"></i>Defense</span><span class=v>12¢</span></div><div class=lg><span class=k><i style="background:#b98cff"></i>Medicaid</span><span class=v>10¢</span></div><div class=lg><span class=k><i style="background:#4fd1a5"></i>Veterans</span><span class=v>5¢</span></div><div class=lg><span class=k><i style="background:#8c9097"></i>Everything else</span><span class=v>22¢</span></div><div class=mini>Per $1 of FY2025 federal outlays ($7.01 trillion). Rounded to whole cents.</div></div></div>',
    '<div class="tag ghost" style="color:#ff5a4e;border-color:#ff5a4e">Stop 1 of 5</div>\n<h2>Social Security</h2><div class=amt style="color:#ff5a4e">22¢</div><div class=pct>$1.57 TRILLION</div><p>The single biggest line: monthly checks to retirees, disabled workers and survivors.</p><div class=finding><div class=lab>Trail note</div><div class=t>It\'s funded mainly by the payroll tax on your paycheck, not the income tax.</div></div>',
    '<div class="tag ghost" style="color:#f2b84b;border-color:#f2b84b">Stop 2 of 5</div>\n<h2>Interest on the debt</h2><div class=amt style="color:#f2b84b">15¢</div><div class=pct>$1.03 TRILLION</div><p>It buys nothing: no roads, no troops, no care. It\'s the cost of money borrowed in past years.</p><p><b>It\'s now bigger than Medicare and bigger than the entire military budget.</b></p><div class=finding><div class=lab>Trail note</div><div class=t>Interest ($1,028B) beat defense ($868B) by $160 billion.</div></div>',
    '<div class="tag ghost" style="color:#6aa9ff;border-color:#6aa9ff">Stop 3 of 5</div>\n<h2>Health care</h2><div class=amt style="color:#6aa9ff">24¢</div><div class=pct>MEDICARE + MEDICAID</div>\n<div class=taxrow>\n <div class=tx><div class=l>Medicare</div><div class=n>14¢</div><div class=d>$992 billion. Mostly people 65 and older.</div></div>\n <div class=tx><div class=l>Medicaid</div><div class=n>10¢</div><div class=d>$668 billion. Low-income and disabled Americans.</div></div>\n</div>\n<div class=finding><div class=lab>Trail note</div><div class=t>Add them together and health care costs more than Social Security.</div></div>',
    '<div class="tag ghost" style="color:#c9c5ba;border-color:#c9c5ba">Stop 4 of 5</div>\n<h2>Defense &amp; veterans</h2><div class=amt style="color:#c9c5ba">17¢</div><div class=pct>MILITARY + VETERANS AFFAIRS</div>\n<div class=taxrow>\n <div class=tx><div class=l>Defense</div><div class=n>12¢</div><div class=d>$868 billion for the Department of Defense military.</div></div>\n <div class=tx><div class=l>Veterans</div><div class=n>5¢</div><div class=d>$377 billion for the Department of Veterans Affairs.</div></div>\n</div>\n<div class=finding><div class=lab>Trail note</div><div class=t>Defense now ranks fourth, behind Social Security, interest and Medicare.</div></div>',
    '<div class="tag ghost" style="color:#8c9097;border-color:#8c9097">Stop 5 of 5</div>\n<h2>Everything else</h2><div class=amt style="color:#8c9097">22¢</div><div class=pct>$1.51 TRILLION</div><p>Every other agency and program: agriculture, homeland security, refundable tax credits, the EPA, education, and more.</p><div class=finding><div class=lab>Trail note</div><div class=t>The entire Department of Education: about half a cent ($35 billion).</div></div>',
    '<div class=tag>Detour</div>\n<h2>Where the dollar<br>came from</h2>\n<div class=cmp><div class="cb"><div class=lbl>75¢</div><div class=col style="height:100%"></div></div><div class="cb hot"><div class=lbl>25¢</div><div class=col style="height:33%"></div></div></div><div class=xax><span>Taxes collected</span><span>Borrowed</span></div>\n<div class=finding><div class=lab>Trail note</div><div class=t>The government took in $5.2 trillion and spent $7.0 trillion. The $1.8 trillion gap was borrowed, which feeds next year\'s interest bill.</div></div>',
    '<div class=tag>End of the trail</div>\n<div class=hook style="font-size:92px">A quarter of it borrowed.<br><em>15¢ to pay for past borrowing.</em></div>\n<div class=cta>Send this to the friend<br>who argues about <em>the budget.</em></div>\n<div class=src>Follow @dollartrail: we follow one price to the end, every day.<br><br>Source: CBO, &ldquo;Monthly Budget Review: Summary for Fiscal Year 2025&rdquo; (Nov. 2025). Defense = DoD military.</div>',
]
