"""Archived example post. Slides are pre-rendered HTML strings; new posts should use the helpers in tools/lib.py."""
import sys, pathlib; sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[2] / "tools"))
from lib import *

ACCOUNT = 'dollartrail'
TRAIL = '003'
FOLLOWING = '$1 of food spending'
SOURCES = ['https://ers.usda.gov/data-products/food-dollar/summary-findings']

CAPTION = 'You spent $1 on food. The farmer got 11.8¢. ...'

SLIDES = [
    '<div class=tag>Trail No. 003</div>\n<div class=hook>You spent <em>$1</em> on food.</div>\n<div class=hook2>The farmer got 11.8&cent;.<br>Who got the rest?</div>\n<div class=mini style="margin-top:60px">Source: USDA Economic Research Service, Food Dollar Series, 2024 data (released March 2026)</div>',
    '<div class=tag>Where you ate matters</div>\n<h2>The farmer\'s cut</h2>\n<div class=cmp><div class="cb"><div class=lbl>18.5¢</div><div class=col style="height:100%"></div></div><div class="cb hot"><div class=lbl>7.1¢</div><div class=col style="height:38%"></div></div></div><div class=xax><span>Grocery store</span><span>Restaurant</span></div>\n<div class=finding><div class=lab>Trail note</div><div class=t>At a restaurant, you\'re mostly paying for cooking, service, rent and convenience. The food itself is a small slice.</div></div>',
    '<div class=tag>The trail map</div><h2 style="font-size:70px">Follow the<br>whole dollar</h2>\n<div class=wrap><div class=gallon style="height:640px"><div class=seg style="height:247px;background:#ff5a4e;font-size:30px">38.6¢</div><div class=seg style="height:103px;background:#f2b84b;font-size:30px">16.1¢</div><div class=seg style="height:88px;background:#6aa9ff;font-size:30px">13.8¢</div><div class=seg style="height:40px;background:#b98cff;font-size:22px">6.3¢</div><div class=seg style="height:43px;background:#4fd1a5;font-size:22px">6.7¢</div><div class=seg style="height:19px;background:#c9c5ba;font-size:22px"></div><div class=seg style="height:99px;background:#8c9097;font-size:30px">15.5¢</div></div><div class=legend><div class=lg><span class=k><i style="background:#ff5a4e"></i>Restaurants</span><span class=v>38.6¢</span></div><div class=lg><span class=k><i style="background:#f2b84b"></i>Food processing</span><span class=v>16.1¢</span></div><div class=lg><span class=k><i style="background:#6aa9ff"></i>Grocery &amp; retail</span><span class=v>13.8¢</span></div><div class=lg><span class=k><i style="background:#b98cff"></i>Wholesale</span><span class=v>6.3¢</span></div><div class=lg><span class=k><i style="background:#4fd1a5"></i>Farms</span><span class=v>6.7¢</span></div><div class=lg><span class=k><i style="background:#c9c5ba"></i>Agribusiness</span><span class=v>3.0¢</span></div><div class=lg><span class=k><i style="background:#8c9097"></i>Everything else</span><span class=v>15.5¢</span></div><div class=mini>Value added per $1, 2024. Everything else = transport, energy, finance, ads, legal.</div></div></div>',
    '<div class="tag ghost" style="color:#ff5a4e;border-color:#ff5a4e">Stop 1 of 3</div>\n<h2>Restaurants</h2><div class=amt style="color:#ff5a4e">38.6¢</div><div class=pct>FOOD SERVICE</div><p>The biggest slice of America\'s food dollar goes to the people who cook and serve it: restaurants, cafeterias, takeout.</p><div class=finding><div class=lab>Trail note</div><div class=t>That\'s more than farms, processors and grocery stores combined.</div></div>',
    '<div class="tag ghost" style="color:#f2b84b;border-color:#f2b84b">Stop 2 of 3</div>\n<h2>Food processing</h2><div class=amt style="color:#f2b84b">16.1¢</div><div class=pct>FACTORIES &amp; PLANTS</div><p>Turning wheat into bread, hogs into bacon, milk into cheese, and corn into the cereal aisle.</p><div class=finding><div class=lab>Trail note</div><div class=t>Processing adds more than twice as much value as the farms themselves (6.7¢).</div></div>',
    '<div class="tag ghost" style="color:#6aa9ff;border-color:#6aa9ff">Stop 3 of 3</div>\n<h2>Stores &amp; distributors</h2><div class=amt style="color:#6aa9ff">20.1¢</div><div class=pct>RETAIL 13.8¢ + WHOLESALE 6.3¢</div><p>The warehouses, trucks-to-shelf distributors and grocery stores that get food from the plant to your cart.</p><div class=finding><div class=lab>Trail note</div><div class=t>Retail and wholesale together take about a fifth of every food dollar.</div></div>',
    '<div class=tag>End of the trail</div>\n<div class=hook style="font-size:92px">More than half goes to restaurants and processors.<br><em>Farms add just 6.7¢.</em></div>\n<div class=cta>Send this to the friend<br>who blames <em>farmers</em> for food prices.</div>\n<div class=src>Follow @dollartrail: we follow one price to the end, every day.<br><br>Source: USDA ERS Food Dollar Series (2024 data, March 2026 release).</div>',
]
