"""Archived example post. Slides are pre-rendered HTML strings; new posts should use the helpers in tools/lib.py."""
import sys, pathlib; sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[2] / "tools"))
from lib import *

ACCOUNT = 'dollartrail'
TRAIL = '004'
FOLLOWING = '1 month of electricity'
SOURCES = ['https://www.eia.gov/energyexplained/electricity/prices-and-factors-affecting-prices.php', 'https://www.eia.gov/todayinenergy/detail.php?id=65244']

CAPTION = 'Your electric bill, followed: 56% makes the power, 44% gets it to your house. ...'

SLIDES = [
    '<div class=tag>Trail No. 004</div>\n<div class=hook>Your electric bill: <em>$144</em> a month.</div>\n<div class=hook2>Here\'s what you\'re actually paying for.</div>\n<div class=mini style="margin-top:60px">Source: U.S. Energy Information Administration. $144 = 2024 average U.S. residential bill, the latest full year.</div>',
    '<div class=tag>The trail map</div><h2 style="font-size:70px">One bill.<br>Three stops.</h2>\n<div class=wrap><div class=gallon style="height:760px"><div class=seg style="height:426px;background:#ff5a4e;font-size:30px">56%</div><div class=seg style="height:228px;background:#f2b84b;font-size:30px">30%</div><div class=seg style="height:106px;background:#6aa9ff;font-size:30px">14%</div></div><div class=legend><div class=lg><span class=k><i style="background:#ff5a4e"></i>Generation</span><span class=v>$80.64</span></div><div class=lg><span class=k><i style="background:#f2b84b"></i>Distribution</span><span class=v>$43.20</span></div><div class=lg><span class=k><i style="background:#6aa9ff"></i>Transmission</span><span class=v>$20.16</span></div><div class=lg><span class=k><i style="background:transparent"></i>Total</span><span class=v>$144.00</span></div><div class=mini>EIA\'s 2025 breakdown of the average U.S. electricity price, applied to the $144 average bill.</div></div></div>',
    '<div class="tag ghost" style="color:#ff5a4e;border-color:#ff5a4e">Stop 1 of 3</div>\n<h2>Making the power</h2><div class=amt style="color:#ff5a4e">$80.64</div><div class=pct>GENERATION &middot; 56%</div><p>Power plants and the fuel they burn: natural gas, coal, nuclear, wind, solar and hydro.</p><div class=finding><div class=lab>Trail note</div><div class=t>Generation is the largest piece of the price, but not the whole story.</div></div>',
    '<div class="tag ghost" style="color:#f2b84b;border-color:#f2b84b">Stop 2 of 3</div>\n<h2>The wires on your street</h2><div class=amt style="color:#f2b84b">$43.20</div><div class=pct>DISTRIBUTION &middot; 30%</div><p>Local poles, lines, transformers and substations, plus the crews who rebuild them after storms.</p><div class=finding><div class=lab>Trail note</div><div class=t>EIA reports utilities now spend more on distribution than on transmission or power production.</div></div>',
    '<div class="tag ghost" style="color:#6aa9ff;border-color:#6aa9ff">Stop 3 of 3</div>\n<h2>The long-distance lines</h2><div class=amt style="color:#6aa9ff">$20.16</div><div class=pct>TRANSMISSION &middot; 14%</div><p>High-voltage lines that carry power from plants, sometimes hundreds of miles away, to your area.</p><div class=finding><div class=lab>Trail note</div><div class=t>Together, getting power to your house costs 44% of your bill.</div></div>',
    '<div class=tag>Detour</div>\n<h2>Why the bill<br>keeps climbing</h2>\n<div class=cmp><div class="cb"><div class=lbl>16.0¢</div><div class=col style="height:92%"></div></div><div class="cb"><div class=lbl>16.5¢</div><div class=col style="height:95%"></div></div><div class="cb hot"><div class=lbl>17.3¢</div><div class=col style="height:100%"></div></div></div><div class=xax><span>2023</span><span>2024</span><span>2025</span></div>\n<div class=finding><div class=lab>Trail note</div><div class=t>Average U.S. residential price per kWh, by year. And it\'s still rising: July 2026 was up 4.9% from July 2025. EIA points to utilities replacing aging infrastructure.</div></div>',
    '<div class=tag>End of the trail</div>\n<div class=hook style="font-size:96px">Over half makes the power.<br><em>The rest gets it to your door.</em></div>\n<div class=cta>Send this to the friend<br>who just opened <em>their bill.</em></div>\n<div class=src>Follow @dollartrail: we follow one price to the end, every day.<br><br>Source: U.S. EIA, Energy Explained: electricity prices (AEO 2026, Table 8); Today in Energy (2024 bills); Electricity Monthly Update (Sept. 2026).</div>',
]
