import sys, pathlib; sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[2] / "tools"))
from lib import *

ACCOUNT = 'dollartrail'
TRAIL = '012'
FOLLOWING = 'one Spotify stream'
SOURCES = ['https://loudandclear.byspotify.com/',
           'https://loudandclear.byspotify.com/takeaways/',
           'https://loudandclear.byspotify.com/process/',
           'https://loudandclear.byspotify.com/payouts/']

CAPTION = """Spotify doesn't pay a set price per stream. It paid the music industry more than $11 billion in 2025, split by each artist's share of all streams. Artists with 1 in every million streams generated over $11,000 on average.

Data: Spotify, Loud & Clear (2025 royalty data).

How many streams do you think your favorite small artist gets in a year?

#spotify #musicindustry #streaming #musicbusiness #artists #dollartrail"""

SLIDES = [
    '<div class=tag>Trail No. 012</div>\n<div class=hook style="font-size:112px">One Spotify stream pays the artist <em>&hellip;no set price.</em></div>\n<div class=hook2>There\'s no per-stream rate. Here\'s how the money moves.</div>\n<div class=mini style="margin-top:60px">Source: Spotify, Loud &amp; Clear (2025 royalty data). All dollar figures are royalties generated on Spotify alone.</div>',
    '<div class=tag>The trail map</div><h2 style="font-size:70px">Your stream joins<br>a pool.</h2>\n<ul class=steps style="margin-top:30px;list-style:none;padding:0">'
    '<li style="margin-bottom:34px"><span style="color:#ff5a4e;font-family:Anton;font-size:56px">1&nbsp;</span><span style="font-size:42px">Spotify pays out a <b>royalty pool</b>.</span></li>'
    '<li style="margin-bottom:34px"><span style="color:#f2b84b;font-family:Anton;font-size:56px">2&nbsp;</span><span style="font-size:42px">Spotify counts every artist\'s <b>share of all streams</b>.</span></li>'
    '<li style="margin-bottom:34px"><span style="color:#6aa9ff;font-family:Anton;font-size:56px">3&nbsp;</span><span style="font-size:42px">Each gets that <b>share of the pool</b>.</span></li>'
    '<li><span style="color:#4fd1a5;font-family:Anton;font-size:56px">4&nbsp;</span><span style="font-size:42px">It goes to <b>artists, songwriters and rightsholders</b>.</span></li></ul>'
    + note("So one stream's value depends on how many streams everyone else had."),
    stop(1, 4, "The pool", "$11B+", "PAID TO THE MUSIC INDUSTRY IN 2025",
         ["Spotify says it paid the music industry more than $11 billion last year, and nearly $70 billion to date."],
         "Spotify says it accounts for about 30% of global recorded music revenue.", R),
    stop(2, 4, "Your slice", "1% &rarr; 1%", "SHARE OF STREAMS = SHARE OF THE POOL",
         ["Spotify&rsquo;s own example: &ldquo;If your music accounts for 1% of all streams, you get roughly 1% of the royalty pool.&rdquo;"],
         "That's called streamshare. No stream has a fixed price tag.", Y),
    stop(3, 4, "1 in a million", "$11,000+", "AVERAGE GENERATED, 2025",
         ["Artists who accounted for 1 in every 1 million streams on Spotify generated over $11,000 on average in 2025."],
         "Royalties generated on Spotify, before any splits the artist has with others.", BL),
    '<div class="tag ghost" style="color:#4fd1a5;border-color:#4fd1a5">Stop 4 of 4</div>\n<h2>Who gets the big checks</h2>\n<div class=taxrow>\n <div class=tx><div class=l>$100K+ a year</div><div class=n>13,800+</div><div class=d>artists generated at least $100,000 from Spotify alone in 2025.</div></div>\n <div class=tx><div class=l>$1M+ a year</div><div class=n>1,500+</div><div class=d>artists generated over $1 million in royalties from Spotify alone.</div></div>\n</div>\n' + note("Roughly half of royalties were generated by independent artists and labels."),
    '<div class=tag>Detour</div>\n<h2>Songwriters get paid too</h2><div class=amt style="color:#b98cff">~$5B</div><div class=pct>TO PUBLISHERS + SONGWRITER GROUPS, PAST TWO YEARS</div>\n<p>A song has two sides: the recording and the composition. Spotify pays publishers and the organizations that represent songwriters separately.</p>' + note("Spotify says publishing royalties are up 2.5x over the past five years."),
    '<div class=tag>End of the trail</div>\n<div class=hook style="font-size:92px">A stream has no price.<br><em>It\'s a share of $11 billion.</em></div>\n<div class=cta>Send this to the friend<br>who asks what <em>one stream</em> pays.</div>\n<div class=src>' + DT_FOLLOW + '<br><br>Source: Spotify, Loud &amp; Clear, 2025 royalty data (loudandclear.byspotify.com): Takeaways, Payouts and Process pages. Figures are Spotify-only royalties generated, as reported by Spotify.</div>',
]
